### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by AKRFranko** [mixu/nwm#44]
I am sorry for this, but I have searched for your contact information and got tired of searching. 

Because I want to THANK YOU!

You cannot imagine what doors and mental pathways you have opened up and illuminated for me with this project. This is way more than a nodejs dwm clone to me, this is example code to get me started on a bigger idea, which I had no clue how to start seeing as my background is mostly with front-end web technologies rather than C or this kind of stuff. 

You sir, are fuckin' awesome!

**Comment by mixu** [comment]
Awesome, glad to hear that!
