### ISSUE TITLE
Error log?

### ISSUE THREAD

**Issue by andrew222651** [mixu/nwm#48]
I'm trying to develop a new layout. When I switch to the layout, nwm crashes so there must be some error in the layout. Does nwm have a log file where I can see why it's crashing?

**Comment by ashnur** [comment]
Yes, if you start it something like this: 

``` bash
exec /usr/local/bin/node ~/mnt/nwm-user/nwm-user.js 2>~/nwm.err.log 1>~/nwm.log
```

Obviously you will have to change the paths so it makes sense on your system.

**Comment by mixu** [comment]
Another tip: it may be easier to use Xephyr to test your layout so that you don't need to keep restarting your X session - https://github.com/mixu/nwm#running-under-a-secondary-x11-server-xephyr

**Comment by andrew222651** [comment]
Thanks all
